// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/hathora/ci/internal/sdk/models/shared"
	"net/http"
)

type CreateRoomDeprecatedGlobals struct {
	AppID *string `pathParam:"style=simple,explode=false,name=appId"`
}

func (o *CreateRoomDeprecatedGlobals) GetAppID() *string {
	if o == nil {
		return nil
	}
	return o.AppID
}

type CreateRoomDeprecatedRequest struct {
	AppID            *string                 `pathParam:"style=simple,explode=false,name=appId"`
	RoomID           *string                 `queryParam:"style=form,explode=true,name=roomId"`
	CreateRoomParams shared.CreateRoomParams `request:"mediaType=application/json"`
}

func (o *CreateRoomDeprecatedRequest) GetAppID() *string {
	if o == nil {
		return nil
	}
	return o.AppID
}

func (o *CreateRoomDeprecatedRequest) GetRoomID() *string {
	if o == nil {
		return nil
	}
	return o.RoomID
}

func (o *CreateRoomDeprecatedRequest) GetCreateRoomParams() shared.CreateRoomParams {
	if o == nil {
		return shared.CreateRoomParams{}
	}
	return o.CreateRoomParams
}

type CreateRoomDeprecatedResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	RoomID      *string
}

func (o *CreateRoomDeprecatedResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *CreateRoomDeprecatedResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *CreateRoomDeprecatedResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *CreateRoomDeprecatedResponse) GetRoomID() *string {
	if o == nil {
		return nil
	}
	return o.RoomID
}
