// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/hathora/ci/internal/sdk/internal/utils"
	"github.com/hathora/ci/internal/sdk/models/components"
)

type CreatePublicLobbyDeprecatedGlobals struct {
	AppID *string `pathParam:"style=simple,explode=false,name=appId"`
}

func (o *CreatePublicLobbyDeprecatedGlobals) GetAppID() *string {
	if o == nil {
		return nil
	}
	return o.AppID
}

type CreatePublicLobbyDeprecatedSecurity struct {
	PlayerAuth string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

func (o *CreatePublicLobbyDeprecatedSecurity) GetPlayerAuth() string {
	if o == nil {
		return ""
	}
	return o.PlayerAuth
}

type CreatePublicLobbyDeprecatedRequest struct {
	AppID  *string            `pathParam:"style=simple,explode=false,name=appId"`
	Region *components.Region `queryParam:"style=form,explode=true,name=region"`
	Local  *bool              `default:"false" queryParam:"style=form,explode=true,name=local"`
}

func (c CreatePublicLobbyDeprecatedRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreatePublicLobbyDeprecatedRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *CreatePublicLobbyDeprecatedRequest) GetAppID() *string {
	if o == nil {
		return nil
	}
	return o.AppID
}

func (o *CreatePublicLobbyDeprecatedRequest) GetRegion() *components.Region {
	if o == nil {
		return nil
	}
	return o.Region
}

func (o *CreatePublicLobbyDeprecatedRequest) GetLocal() *bool {
	if o == nil {
		return nil
	}
	return o.Local
}
