// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/hathora/ci/internal/sdk/models/components"
)

type CreateLocalLobbyGlobals struct {
	AppID *string `pathParam:"style=simple,explode=false,name=appId"`
}

func (o *CreateLocalLobbyGlobals) GetAppID() *string {
	if o == nil {
		return nil
	}
	return o.AppID
}

type CreateLocalLobbySecurity struct {
	PlayerAuth string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

func (o *CreateLocalLobbySecurity) GetPlayerAuth() string {
	if o == nil {
		return ""
	}
	return o.PlayerAuth
}

type CreateLocalLobbyRequestBody struct {
	// User input to initialize the game state. Object must be smaller than 64KB.
	InitialConfig any               `json:"initialConfig"`
	Region        components.Region `json:"region"`
}

func (o *CreateLocalLobbyRequestBody) GetInitialConfig() any {
	if o == nil {
		return nil
	}
	return o.InitialConfig
}

func (o *CreateLocalLobbyRequestBody) GetRegion() components.Region {
	if o == nil {
		return components.Region("")
	}
	return o.Region
}

type CreateLocalLobbyRequest struct {
	AppID       *string                     `pathParam:"style=simple,explode=false,name=appId"`
	RoomID      *string                     `queryParam:"style=form,explode=true,name=roomId"`
	RequestBody CreateLocalLobbyRequestBody `request:"mediaType=application/json"`
}

func (o *CreateLocalLobbyRequest) GetAppID() *string {
	if o == nil {
		return nil
	}
	return o.AppID
}

func (o *CreateLocalLobbyRequest) GetRoomID() *string {
	if o == nil {
		return nil
	}
	return o.RoomID
}

func (o *CreateLocalLobbyRequest) GetRequestBody() CreateLocalLobbyRequestBody {
	if o == nil {
		return CreateLocalLobbyRequestBody{}
	}
	return o.RequestBody
}
