// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/hathora/ci/internal/sdk/models/components"
)

type CreateRoomGlobals struct {
	AppID *string `pathParam:"style=simple,explode=false,name=appId"`
}

func (o *CreateRoomGlobals) GetAppID() *string {
	if o == nil {
		return nil
	}
	return o.AppID
}

type CreateRoomRequest struct {
	AppID            *string                     `pathParam:"style=simple,explode=false,name=appId"`
	RoomID           *string                     `queryParam:"style=form,explode=true,name=roomId"`
	CreateRoomParams components.CreateRoomParams `request:"mediaType=application/json"`
}

func (o *CreateRoomRequest) GetAppID() *string {
	if o == nil {
		return nil
	}
	return o.AppID
}

func (o *CreateRoomRequest) GetRoomID() *string {
	if o == nil {
		return nil
	}
	return o.RoomID
}

func (o *CreateRoomRequest) GetCreateRoomParams() components.CreateRoomParams {
	if o == nil {
		return components.CreateRoomParams{}
	}
	return o.CreateRoomParams
}
