// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/hathora/ci/internal/sdk/models/shared"
	"net/http"
)

type CreateLobbyDeprecatedGlobals struct {
	AppID *string `pathParam:"style=simple,explode=false,name=appId"`
}

func (o *CreateLobbyDeprecatedGlobals) GetAppID() *string {
	if o == nil {
		return nil
	}
	return o.AppID
}

type CreateLobbyDeprecatedSecurity struct {
	PlayerAuth string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

func (o *CreateLobbyDeprecatedSecurity) GetPlayerAuth() string {
	if o == nil {
		return ""
	}
	return o.PlayerAuth
}

type CreateLobbyDeprecatedRequest struct {
	AppID             *string                  `pathParam:"style=simple,explode=false,name=appId"`
	RoomID            *string                  `queryParam:"style=form,explode=true,name=roomId"`
	CreateLobbyParams shared.CreateLobbyParams `request:"mediaType=application/json"`
}

func (o *CreateLobbyDeprecatedRequest) GetAppID() *string {
	if o == nil {
		return nil
	}
	return o.AppID
}

func (o *CreateLobbyDeprecatedRequest) GetRoomID() *string {
	if o == nil {
		return nil
	}
	return o.RoomID
}

func (o *CreateLobbyDeprecatedRequest) GetCreateLobbyParams() shared.CreateLobbyParams {
	if o == nil {
		return shared.CreateLobbyParams{}
	}
	return o.CreateLobbyParams
}

type CreateLobbyDeprecatedResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	Lobby       *shared.Lobby
}

func (o *CreateLobbyDeprecatedResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *CreateLobbyDeprecatedResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *CreateLobbyDeprecatedResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *CreateLobbyDeprecatedResponse) GetLobby() *shared.Lobby {
	if o == nil {
		return nil
	}
	return o.Lobby
}
