// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/hathora/ci/internal/sdk/models/shared"
	"net/http"
)

type CreatePublicLobbyGlobals struct {
	AppID *string `pathParam:"style=simple,explode=false,name=appId"`
}

func (o *CreatePublicLobbyGlobals) GetAppID() *string {
	if o == nil {
		return nil
	}
	return o.AppID
}

type CreatePublicLobbySecurity struct {
	PlayerAuth string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

func (o *CreatePublicLobbySecurity) GetPlayerAuth() string {
	if o == nil {
		return ""
	}
	return o.PlayerAuth
}

type CreatePublicLobbyRequestBody struct {
	// User input to initialize the game state. Object must be smaller than 64KB.
	InitialConfig any           `json:"initialConfig"`
	Region        shared.Region `json:"region"`
}

func (o *CreatePublicLobbyRequestBody) GetInitialConfig() any {
	if o == nil {
		return nil
	}
	return o.InitialConfig
}

func (o *CreatePublicLobbyRequestBody) GetRegion() shared.Region {
	if o == nil {
		return shared.Region("")
	}
	return o.Region
}

type CreatePublicLobbyRequest struct {
	AppID       *string                      `pathParam:"style=simple,explode=false,name=appId"`
	RoomID      *string                      `queryParam:"style=form,explode=true,name=roomId"`
	RequestBody CreatePublicLobbyRequestBody `request:"mediaType=application/json"`
}

func (o *CreatePublicLobbyRequest) GetAppID() *string {
	if o == nil {
		return nil
	}
	return o.AppID
}

func (o *CreatePublicLobbyRequest) GetRoomID() *string {
	if o == nil {
		return nil
	}
	return o.RoomID
}

func (o *CreatePublicLobbyRequest) GetRequestBody() CreatePublicLobbyRequestBody {
	if o == nil {
		return CreatePublicLobbyRequestBody{}
	}
	return o.RequestBody
}

type CreatePublicLobbyResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	Lobby       *shared.Lobby
}

func (o *CreatePublicLobbyResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *CreatePublicLobbyResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *CreatePublicLobbyResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *CreatePublicLobbyResponse) GetLobby() *shared.Lobby {
	if o == nil {
		return nil
	}
	return o.Lobby
}
