// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type DestroyRoomDeprecatedGlobals struct {
	AppID *string `pathParam:"style=simple,explode=false,name=appId"`
}

func (o *DestroyRoomDeprecatedGlobals) GetAppID() *string {
	if o == nil {
		return nil
	}
	return o.AppID
}

type DestroyRoomDeprecatedRequest struct {
	AppID  *string `pathParam:"style=simple,explode=false,name=appId"`
	RoomID string  `pathParam:"style=simple,explode=false,name=roomId"`
}

func (o *DestroyRoomDeprecatedRequest) GetAppID() *string {
	if o == nil {
		return nil
	}
	return o.AppID
}

func (o *DestroyRoomDeprecatedRequest) GetRoomID() string {
	if o == nil {
		return ""
	}
	return o.RoomID
}
