// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type GetAppGlobals struct {
	AppID *string `pathParam:"style=simple,explode=false,name=appId"`
}

func (o *GetAppGlobals) GetAppID() *string {
	if o == nil {
		return nil
	}
	return o.AppID
}

type GetAppRequest struct {
	AppID *string `pathParam:"style=simple,explode=false,name=appId"`
}

func (o *GetAppRequest) GetAppID() *string {
	if o == nil {
		return nil
	}
	return o.AppID
}
