// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type GetBuildGlobals struct {
	OrgID *string `queryParam:"style=form,explode=true,name=orgId"`
}

func (o *GetBuildGlobals) GetOrgID() *string {
	if o == nil {
		return nil
	}
	return o.OrgID
}

type GetBuildRequest struct {
	BuildID string  `pathParam:"style=simple,explode=false,name=buildId"`
	OrgID   *string `queryParam:"style=form,explode=true,name=orgId"`
}

func (o *GetBuildRequest) GetBuildID() string {
	if o == nil {
		return ""
	}
	return o.BuildID
}

func (o *GetBuildRequest) GetOrgID() *string {
	if o == nil {
		return nil
	}
	return o.OrgID
}
