// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type GetConnectionInfoDeprecatedGlobals struct {
	AppID *string `pathParam:"style=simple,explode=false,name=appId"`
}

func (o *GetConnectionInfoDeprecatedGlobals) GetAppID() *string {
	if o == nil {
		return nil
	}
	return o.AppID
}

type GetConnectionInfoDeprecatedRequest struct {
	AppID  *string `pathParam:"style=simple,explode=false,name=appId"`
	RoomID string  `pathParam:"style=simple,explode=false,name=roomId"`
}

func (o *GetConnectionInfoDeprecatedRequest) GetAppID() *string {
	if o == nil {
		return nil
	}
	return o.AppID
}

func (o *GetConnectionInfoDeprecatedRequest) GetRoomID() string {
	if o == nil {
		return ""
	}
	return o.RoomID
}
