// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type GetInactiveRoomsForProcessGlobals struct {
	AppID *string `pathParam:"style=simple,explode=false,name=appId"`
}

func (o *GetInactiveRoomsForProcessGlobals) GetAppID() *string {
	if o == nil {
		return nil
	}
	return o.AppID
}

type GetInactiveRoomsForProcessRequest struct {
	AppID     *string `pathParam:"style=simple,explode=false,name=appId"`
	ProcessID string  `pathParam:"style=simple,explode=false,name=processId"`
}

func (o *GetInactiveRoomsForProcessRequest) GetAppID() *string {
	if o == nil {
		return nil
	}
	return o.AppID
}

func (o *GetInactiveRoomsForProcessRequest) GetProcessID() string {
	if o == nil {
		return ""
	}
	return o.ProcessID
}
