// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/hathora/ci/internal/sdk/internal/utils"
)

type GetLogsForProcessGlobals struct {
	AppID *string `pathParam:"style=simple,explode=false,name=appId"`
}

func (o *GetLogsForProcessGlobals) GetAppID() *string {
	if o == nil {
		return nil
	}
	return o.AppID
}

type GetLogsForProcessRequest struct {
	AppID     *string `pathParam:"style=simple,explode=false,name=appId"`
	ProcessID string  `pathParam:"style=simple,explode=false,name=processId"`
	Follow    *bool   `queryParam:"style=form,explode=true,name=follow"`
	TailLines *int    `default:"100" queryParam:"style=form,explode=true,name=tailLines"`
}

func (g GetLogsForProcessRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetLogsForProcessRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *GetLogsForProcessRequest) GetAppID() *string {
	if o == nil {
		return nil
	}
	return o.AppID
}

func (o *GetLogsForProcessRequest) GetProcessID() string {
	if o == nil {
		return ""
	}
	return o.ProcessID
}

func (o *GetLogsForProcessRequest) GetFollow() *bool {
	if o == nil {
		return nil
	}
	return o.Follow
}

func (o *GetLogsForProcessRequest) GetTailLines() *int {
	if o == nil {
		return nil
	}
	return o.TailLines
}
