// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/hathora/ci/internal/sdk/models/components"
)

type GetLatestProcessesGlobals struct {
	AppID *string `pathParam:"style=simple,explode=false,name=appId"`
}

func (o *GetLatestProcessesGlobals) GetAppID() *string {
	if o == nil {
		return nil
	}
	return o.AppID
}

type GetLatestProcessesRequest struct {
	AppID  *string                    `pathParam:"style=simple,explode=false,name=appId"`
	Status []components.ProcessStatus `queryParam:"style=form,explode=true,name=status"`
	Region []components.Region        `queryParam:"style=form,explode=true,name=region"`
}

func (o *GetLatestProcessesRequest) GetAppID() *string {
	if o == nil {
		return nil
	}
	return o.AppID
}

func (o *GetLatestProcessesRequest) GetStatus() []components.ProcessStatus {
	if o == nil {
		return nil
	}
	return o.Status
}

func (o *GetLatestProcessesRequest) GetRegion() []components.Region {
	if o == nil {
		return nil
	}
	return o.Region
}
