// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type GetLatestDeploymentGlobals struct {
	AppID *string `pathParam:"style=simple,explode=false,name=appId"`
}

func (o *GetLatestDeploymentGlobals) GetAppID() *string {
	if o == nil {
		return nil
	}
	return o.AppID
}

type GetLatestDeploymentRequest struct {
	AppID *string `pathParam:"style=simple,explode=false,name=appId"`
}

func (o *GetLatestDeploymentRequest) GetAppID() *string {
	if o == nil {
		return nil
	}
	return o.AppID
}
