// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/hathora/ci/internal/sdk/models/components"
)

type GetProcessesCountExperimentalGlobals struct {
	AppID *string `pathParam:"style=simple,explode=false,name=appId"`
}

func (o *GetProcessesCountExperimentalGlobals) GetAppID() *string {
	if o == nil {
		return nil
	}
	return o.AppID
}

type GetProcessesCountExperimentalRequest struct {
	AppID  *string                    `pathParam:"style=simple,explode=false,name=appId"`
	Status []components.ProcessStatus `queryParam:"style=form,explode=true,name=status"`
	Region []components.Region        `queryParam:"style=form,explode=true,name=region"`
}

func (o *GetProcessesCountExperimentalRequest) GetAppID() *string {
	if o == nil {
		return nil
	}
	return o.AppID
}

func (o *GetProcessesCountExperimentalRequest) GetStatus() []components.ProcessStatus {
	if o == nil {
		return nil
	}
	return o.Status
}

func (o *GetProcessesCountExperimentalRequest) GetRegion() []components.Region {
	if o == nil {
		return nil
	}
	return o.Region
}

// GetProcessesCountExperimentalResponseBody - Ok
type GetProcessesCountExperimentalResponseBody struct {
	Count float64 `json:"count"`
}

func (o *GetProcessesCountExperimentalResponseBody) GetCount() float64 {
	if o == nil {
		return 0.0
	}
	return o.Count
}
