// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type GetPaymentMethodGlobals struct {
	OrgID *string `queryParam:"style=form,explode=true,name=orgId"`
}

func (o *GetPaymentMethodGlobals) GetOrgID() *string {
	if o == nil {
		return nil
	}
	return o.OrgID
}

type GetPaymentMethodRequest struct {
	OrgID *string `queryParam:"style=form,explode=true,name=orgId"`
}

func (o *GetPaymentMethodRequest) GetOrgID() *string {
	if o == nil {
		return nil
	}
	return o.OrgID
}
