// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/hathora/ci/internal/sdk/models/shared"
	"net/http"
)

type GetUserPendingInvitesResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Ok
	PendingOrgInvitesPage *shared.PendingOrgInvitesPage
}

func (o *GetUserPendingInvitesResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetUserPendingInvitesResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetUserPendingInvitesResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetUserPendingInvitesResponse) GetPendingOrgInvitesPage() *shared.PendingOrgInvitesPage {
	if o == nil {
		return nil
	}
	return o.PendingOrgInvitesPage
}
