// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/hathora/ci/internal/sdk/models/components"
)

type ListActivePublicLobbiesDeprecatedV2Globals struct {
	AppID *string `pathParam:"style=simple,explode=false,name=appId"`
}

func (o *ListActivePublicLobbiesDeprecatedV2Globals) GetAppID() *string {
	if o == nil {
		return nil
	}
	return o.AppID
}

type ListActivePublicLobbiesDeprecatedV2Request struct {
	AppID *string `pathParam:"style=simple,explode=false,name=appId"`
	// Region to filter by. If omitted, active public lobbies in all regions will be returned.
	Region *components.Region `queryParam:"style=form,explode=true,name=region"`
}

func (o *ListActivePublicLobbiesDeprecatedV2Request) GetAppID() *string {
	if o == nil {
		return nil
	}
	return o.AppID
}

func (o *ListActivePublicLobbiesDeprecatedV2Request) GetRegion() *components.Region {
	if o == nil {
		return nil
	}
	return o.Region
}
