// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/hathora/ci/internal/sdk/models/shared"
	"net/http"
)

type LoginAnonymousGlobals struct {
	AppID *string `pathParam:"style=simple,explode=false,name=appId"`
}

func (o *LoginAnonymousGlobals) GetAppID() *string {
	if o == nil {
		return nil
	}
	return o.AppID
}

type LoginAnonymousRequest struct {
	AppID *string `pathParam:"style=simple,explode=false,name=appId"`
}

func (o *LoginAnonymousRequest) GetAppID() *string {
	if o == nil {
		return nil
	}
	return o.AppID
}

type LoginAnonymousResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Ok
	PlayerTokenObject *shared.PlayerTokenObject
}

func (o *LoginAnonymousResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *LoginAnonymousResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *LoginAnonymousResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *LoginAnonymousResponse) GetPlayerTokenObject() *shared.PlayerTokenObject {
	if o == nil {
		return nil
	}
	return o.PlayerTokenObject
}
