// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type RejectInviteRequest struct {
	OrgID string `pathParam:"style=simple,explode=false,name=orgId"`
}

func (o *RejectInviteRequest) GetOrgID() string {
	if o == nil {
		return ""
	}
	return o.OrgID
}
