// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type RevokeOrgTokenRequest struct {
	OrgID      string `pathParam:"style=simple,explode=false,name=orgId"`
	OrgTokenID string `pathParam:"style=simple,explode=false,name=orgTokenId"`
}

func (o *RevokeOrgTokenRequest) GetOrgID() string {
	if o == nil {
		return ""
	}
	return o.OrgID
}

func (o *RevokeOrgTokenRequest) GetOrgTokenID() string {
	if o == nil {
		return ""
	}
	return o.OrgTokenID
}
