// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"cloudapi/pkg/models/shared"
	"cloudapi/pkg/utils"
	"net/http"
)

type CreatePublicLobbyDeprecatedGlobals struct {
	AppID *string `pathParam:"style=simple,explode=false,name=appId"`
}

func (o *CreatePublicLobbyDeprecatedGlobals) GetAppID() *string {
	if o == nil {
		return nil
	}
	return o.AppID
}

type CreatePublicLobbyDeprecatedSecurity struct {
	PlayerAuth string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

func (o *CreatePublicLobbyDeprecatedSecurity) GetPlayerAuth() string {
	if o == nil {
		return ""
	}
	return o.PlayerAuth
}

type CreatePublicLobbyDeprecatedRequest struct {
	AppID  *string        `pathParam:"style=simple,explode=false,name=appId"`
	Region *shared.Region `queryParam:"style=form,explode=true,name=region"`
	Local  *bool          `default:"false" queryParam:"style=form,explode=true,name=local"`
}

func (c CreatePublicLobbyDeprecatedRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreatePublicLobbyDeprecatedRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *CreatePublicLobbyDeprecatedRequest) GetAppID() *string {
	if o == nil {
		return nil
	}
	return o.AppID
}

func (o *CreatePublicLobbyDeprecatedRequest) GetRegion() *shared.Region {
	if o == nil {
		return nil
	}
	return o.Region
}

func (o *CreatePublicLobbyDeprecatedRequest) GetLocal() *bool {
	if o == nil {
		return nil
	}
	return o.Local
}

type CreatePublicLobbyDeprecatedResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Ok
	RoomID *string
}

func (o *CreatePublicLobbyDeprecatedResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *CreatePublicLobbyDeprecatedResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *CreatePublicLobbyDeprecatedResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *CreatePublicLobbyDeprecatedResponse) GetRoomID() *string {
	if o == nil {
		return nil
	}
	return o.RoomID
}
