// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"cloudapi/pkg/models/shared"
	"net/http"
)

type GetConnectionInfoGlobals struct {
	AppID *string `pathParam:"style=simple,explode=false,name=appId"`
}

func (o *GetConnectionInfoGlobals) GetAppID() *string {
	if o == nil {
		return nil
	}
	return o.AppID
}

type GetConnectionInfoRequest struct {
	RoomID string  `pathParam:"style=simple,explode=false,name=roomId"`
	AppID  *string `pathParam:"style=simple,explode=false,name=appId"`
}

func (o *GetConnectionInfoRequest) GetRoomID() string {
	if o == nil {
		return ""
	}
	return o.RoomID
}

func (o *GetConnectionInfoRequest) GetAppID() *string {
	if o == nil {
		return nil
	}
	return o.AppID
}

type GetConnectionInfoResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Ok
	ConnectionInfoV2 *shared.ConnectionInfoV2
}

func (o *GetConnectionInfoResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetConnectionInfoResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetConnectionInfoResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetConnectionInfoResponse) GetConnectionInfoV2() *shared.ConnectionInfoV2 {
	if o == nil {
		return nil
	}
	return o.ConnectionInfoV2
}
