// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"cloudapi/pkg/models/shared"
	"net/http"
)

type GetInactiveRoomsForProcessGlobals struct {
	AppID *string `pathParam:"style=simple,explode=false,name=appId"`
}

func (o *GetInactiveRoomsForProcessGlobals) GetAppID() *string {
	if o == nil {
		return nil
	}
	return o.AppID
}

type GetInactiveRoomsForProcessRequest struct {
	ProcessID string  `pathParam:"style=simple,explode=false,name=processId"`
	AppID     *string `pathParam:"style=simple,explode=false,name=appId"`
}

func (o *GetInactiveRoomsForProcessRequest) GetProcessID() string {
	if o == nil {
		return ""
	}
	return o.ProcessID
}

func (o *GetInactiveRoomsForProcessRequest) GetAppID() *string {
	if o == nil {
		return nil
	}
	return o.AppID
}

type GetInactiveRoomsForProcessResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Ok
	RoomWithoutAllocations []shared.RoomWithoutAllocations
}

func (o *GetInactiveRoomsForProcessResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetInactiveRoomsForProcessResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetInactiveRoomsForProcessResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetInactiveRoomsForProcessResponse) GetRoomWithoutAllocations() []shared.RoomWithoutAllocations {
	if o == nil {
		return nil
	}
	return o.RoomWithoutAllocations
}
