// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"cloudapi/pkg/utils"
	"io"
	"net/http"
)

type GetLogsForDeploymentGlobals struct {
	AppID *string `pathParam:"style=simple,explode=false,name=appId"`
}

func (o *GetLogsForDeploymentGlobals) GetAppID() *string {
	if o == nil {
		return nil
	}
	return o.AppID
}

type GetLogsForDeploymentRequest struct {
	DeploymentID int     `pathParam:"style=simple,explode=false,name=deploymentId"`
	AppID        *string `pathParam:"style=simple,explode=false,name=appId"`
	Follow       *bool   `default:"false" queryParam:"style=form,explode=true,name=follow"`
	TailLines    *int    `default:"100" queryParam:"style=form,explode=true,name=tailLines"`
}

func (g GetLogsForDeploymentRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetLogsForDeploymentRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *GetLogsForDeploymentRequest) GetDeploymentID() int {
	if o == nil {
		return 0
	}
	return o.DeploymentID
}

func (o *GetLogsForDeploymentRequest) GetAppID() *string {
	if o == nil {
		return nil
	}
	return o.AppID
}

func (o *GetLogsForDeploymentRequest) GetFollow() *bool {
	if o == nil {
		return nil
	}
	return o.Follow
}

func (o *GetLogsForDeploymentRequest) GetTailLines() *int {
	if o == nil {
		return nil
	}
	return o.TailLines
}

type GetLogsForDeploymentResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Ok
	// The Close method must be called on this field, even if it is not used, to prevent resource leaks.
	Stream io.ReadCloser
}

func (o *GetLogsForDeploymentResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetLogsForDeploymentResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetLogsForDeploymentResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetLogsForDeploymentResponse) GetStream() io.ReadCloser {
	if o == nil {
		return nil
	}
	return o.Stream
}
