// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"cloudapi/pkg/models/shared"
	"cloudapi/pkg/utils"
	"net/http"
)

type GetMetricsGlobals struct {
	AppID *string `pathParam:"style=simple,explode=false,name=appId"`
}

func (o *GetMetricsGlobals) GetAppID() *string {
	if o == nil {
		return nil
	}
	return o.AppID
}

type GetMetricsRequest struct {
	AppID     *string `pathParam:"style=simple,explode=false,name=appId"`
	ProcessID string  `pathParam:"style=simple,explode=false,name=processId"`
	// Available metrics to query over time.
	Metrics []shared.MetricName `queryParam:"style=form,explode=true,name=metrics"`
	// Unix timestamp. Default is current time.
	End *float64 `queryParam:"style=form,explode=true,name=end"`
	// Unix timestamp. Default is -1 hour from `end`.
	Start *float64 `queryParam:"style=form,explode=true,name=start"`
	Step  *int     `default:"60" queryParam:"style=form,explode=true,name=step"`
}

func (g GetMetricsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetMetricsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *GetMetricsRequest) GetAppID() *string {
	if o == nil {
		return nil
	}
	return o.AppID
}

func (o *GetMetricsRequest) GetProcessID() string {
	if o == nil {
		return ""
	}
	return o.ProcessID
}

func (o *GetMetricsRequest) GetMetrics() []shared.MetricName {
	if o == nil {
		return nil
	}
	return o.Metrics
}

func (o *GetMetricsRequest) GetEnd() *float64 {
	if o == nil {
		return nil
	}
	return o.End
}

func (o *GetMetricsRequest) GetStart() *float64 {
	if o == nil {
		return nil
	}
	return o.Start
}

func (o *GetMetricsRequest) GetStep() *int {
	if o == nil {
		return nil
	}
	return o.Step
}

type GetMetricsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Ok
	MetricsData *shared.MetricsData
}

func (o *GetMetricsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetMetricsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetMetricsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetMetricsResponse) GetMetricsData() *shared.MetricsData {
	if o == nil {
		return nil
	}
	return o.MetricsData
}
