// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// Google - Enable google auth for your application.
type Google struct {
	// A Google generated token representing the developer's credentials for [Google's API Console](https://console.cloud.google.com/apis/dashboard?pli=1&project=discourse-login-388921). Learn how to get a `clientId` [here](https://developers.google.com/identity/gsi/web/guides/get-google-api-clientid).
	ClientID string `json:"clientId"`
}

func (o *Google) GetClientID() string {
	if o == nil {
		return ""
	}
	return o.ClientID
}

// AuthConfiguration - Configure [player authentication](https://hathora.dev/docs/lobbies-and-matchmaking/auth-service) for your application. Use Hathora's built-in auth providers or use your own [custom authentication](https://hathora.dev/docs/lobbies-and-matchmaking/auth-service#custom-auth-provider).
type AuthConfiguration struct {
	// Enable google auth for your application.
	Google *Google `json:"google,omitempty"`
	// Construct a type with a set of properties K of type T
	Nickname *RecordStringNever `json:"nickname,omitempty"`
	// Construct a type with a set of properties K of type T
	Anonymous *RecordStringNever `json:"anonymous,omitempty"`
}

func (o *AuthConfiguration) GetGoogle() *Google {
	if o == nil {
		return nil
	}
	return o.Google
}

func (o *AuthConfiguration) GetNickname() *RecordStringNever {
	if o == nil {
		return nil
	}
	return o.Nickname
}

func (o *AuthConfiguration) GetAnonymous() *RecordStringNever {
	if o == nil {
		return nil
	}
	return o.Anonymous
}
