// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type GoogleIDTokenObject struct {
	// A Google-signed OIDC ID token representing a player's authenticated identity. Learn how to get an `idToken` [here](https://cloud.google.com/docs/authentication/get-id-token).
	IDToken string `json:"idToken"`
}

func (o *GoogleIDTokenObject) GetIDToken() string {
	if o == nil {
		return ""
	}
	return o.IDToken
}
