// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type VerificationEmailRequest struct {
	UserID string `json:"userId"`
}

func (o *VerificationEmailRequest) GetUserID() string {
	if o == nil {
		return ""
	}
	return o.UserID
}
