// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type CreatedOrgToken struct {
	PlainTextToken string   `json:"plainTextToken"`
	OrgToken       OrgToken `json:"orgToken"`
}

func (o *CreatedOrgToken) GetPlainTextToken() string {
	if o == nil {
		return ""
	}
	return o.PlainTextToken
}

func (o *CreatedOrgToken) GetOrgToken() OrgToken {
	if o == nil {
		return OrgToken{}
	}
	return o.OrgToken
}
