// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type CreateMultipartBuildParams struct {
	// System generated id for a build. Can also be user defined when creating a build.
	BuildID *string `json:"buildId,omitempty"`
	// Tag to associate an external version with a build. It is accessible via [`GetBuildInfo()`](https://hathora.dev/api#tag/BuildV2/operation/GetBuildInfo).
	BuildTag         *string `json:"buildTag,omitempty"`
	BuildSizeInBytes float64 `json:"buildSizeInBytes"`
}

func (o *CreateMultipartBuildParams) GetBuildID() *string {
	if o == nil {
		return nil
	}
	return o.BuildID
}

func (o *CreateMultipartBuildParams) GetBuildTag() *string {
	if o == nil {
		return nil
	}
	return o.BuildTag
}

func (o *CreateMultipartBuildParams) GetBuildSizeInBytes() float64 {
	if o == nil {
		return 0.0
	}
	return o.BuildSizeInBytes
}
