// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type InvoiceStatus string

const (
	InvoiceStatusPending InvoiceStatus = "pending"
	InvoiceStatusPaid    InvoiceStatus = "paid"
	InvoiceStatusOverdue InvoiceStatus = "overdue"
)

func (e InvoiceStatus) ToPointer() *InvoiceStatus {
	return &e
}
func (e *InvoiceStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "pending":
		fallthrough
	case "paid":
		fallthrough
	case "overdue":
		*e = InvoiceStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for InvoiceStatus: %v", v)
	}
}
