// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type LinkPaymentMethod struct {
	Email *string `json:"email,omitempty"`
}

func (o *LinkPaymentMethod) GetEmail() *string {
	if o == nil {
		return nil
	}
	return o.Email
}
