// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// MetricName - Available metrics to query over time.
type MetricName string

const (
	MetricNameCPU               MetricName = "cpu"
	MetricNameMemory            MetricName = "memory"
	MetricNameRateEgress        MetricName = "rate_egress"
	MetricNameTotalEgress       MetricName = "total_egress"
	MetricNameActiveConnections MetricName = "active_connections"
)

func (e MetricName) ToPointer() *MetricName {
	return &e
}
