// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Organization struct {
	IsSingleTenant   bool   `json:"isSingleTenant"`
	StripeCustomerID string `json:"stripeCustomerId"`
	// System generated unique identifier for an organization. Not guaranteed to have a specific format.
	OrgID string `json:"orgId"`
}

func (o *Organization) GetIsSingleTenant() bool {
	if o == nil {
		return false
	}
	return o.IsSingleTenant
}

func (o *Organization) GetStripeCustomerID() string {
	if o == nil {
		return ""
	}
	return o.StripeCustomerID
}

func (o *Organization) GetOrgID() string {
	if o == nil {
		return ""
	}
	return o.OrgID
}
