// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type PingEndpoints struct {
	Port   float64 `json:"port"`
	Host   string  `json:"host"`
	Region Region  `json:"region"`
}

func (o *PingEndpoints) GetPort() float64 {
	if o == nil {
		return 0.0
	}
	return o.Port
}

func (o *PingEndpoints) GetHost() string {
	if o == nil {
		return ""
	}
	return o.Host
}

func (o *PingEndpoints) GetRegion() Region {
	if o == nil {
		return Region("")
	}
	return o.Region
}
