// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// PlanName - A plan defines how much CPU and memory is required to run an instance of your game server.
//
// `tiny`: shared core, 1gb memory
//
// `small`: 1 core, 2gb memory
//
// `medium`: 2 core, 4gb memory
//
// `large`: 4 core, 8gb memory
type PlanName string

const (
	PlanNameTiny   PlanName = "tiny"
	PlanNameSmall  PlanName = "small"
	PlanNameMedium PlanName = "medium"
	PlanNameLarge  PlanName = "large"
)

func (e PlanName) ToPointer() *PlanName {
	return &e
}
