workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    my-source:
        inputs:
            - location: registry.speakeasyapi.dev/hathora/hathora/my-source:main
        registry:
            location: registry.speakeasyapi.dev/hathora/hathora/my-source
targets:
    hathora-cloud:
        target: go
        source: my-source
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/hathora/hathora/my-source-go-code-samples
            blocking: false
