// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"cloudapi/pkg/utils"
	"time"
)

// State - JSON blob to store metadata for a room. Must be smaller than 1MB.
type State struct {
}

// Lobby - A lobby object allows you to store and manage metadata for your rooms.
type Lobby struct {
	ShortCode *string `json:"shortCode"`
	// JSON blob to store metadata for a room. Must be smaller than 1MB.
	State *State `json:"state,omitempty"`
	// User input to initialize the game state. Object must be smaller than 64KB.
	InitialConfig LobbyInitialConfig `json:"initialConfig"`
	// When the lobby was created.
	CreatedAt time.Time `json:"createdAt"`
	// UserId or email address for the user that created the lobby.
	CreatedBy string `json:"createdBy"`
	// Deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
	Local bool `json:"local"`
	// Types of lobbies a player can create.
	//
	// `private`: the player who created the room must share the roomId with their friends
	//
	// `public`: visible in the public lobby list, anyone can join
	//
	// `local`: for testing with a server running locally
	Visibility LobbyVisibility `json:"visibility"`
	Region     Region          `json:"region"`
	// Unique identifier to a game session or match. Use the default system generated ID or overwrite it with your own.
	// Note: error will be returned if `roomId` is not globally unique.
	RoomID string `json:"roomId"`
	// System generated unique identifier for an application.
	AppID string `json:"appId"`
}

func (l Lobby) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *Lobby) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *Lobby) GetShortCode() *string {
	if o == nil {
		return nil
	}
	return o.ShortCode
}

func (o *Lobby) GetState() *State {
	if o == nil {
		return nil
	}
	return o.State
}

func (o *Lobby) GetInitialConfig() LobbyInitialConfig {
	if o == nil {
		return LobbyInitialConfig{}
	}
	return o.InitialConfig
}

func (o *Lobby) GetCreatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.CreatedAt
}

func (o *Lobby) GetCreatedBy() string {
	if o == nil {
		return ""
	}
	return o.CreatedBy
}

func (o *Lobby) GetLocal() bool {
	if o == nil {
		return false
	}
	return o.Local
}

func (o *Lobby) GetVisibility() LobbyVisibility {
	if o == nil {
		return LobbyVisibility("")
	}
	return o.Visibility
}

func (o *Lobby) GetRegion() Region {
	if o == nil {
		return Region("")
	}
	return o.Region
}

func (o *Lobby) GetRoomID() string {
	if o == nil {
		return ""
	}
	return o.RoomID
}

func (o *Lobby) GetAppID() string {
	if o == nil {
		return ""
	}
	return o.AppID
}
