// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package globals

type Globals struct {
	AppID *string `pathParam:"style=simple,explode=false,name=appId"`
}

func (o *Globals) GetAppID() *string {
	if o == nil {
		return nil
	}
	return o.AppID
}
