// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package globals

type Globals struct {
	OrgID *string `queryParam:"style=form,explode=true,name=orgId"`
	AppID *string `pathParam:"style=simple,explode=false,name=appId"`
}

func (o *Globals) GetOrgID() *string {
	if o == nil {
		return nil
	}
	return o.OrgID
}

func (o *Globals) GetAppID() *string {
	if o == nil {
		return nil
	}
	return o.AppID
}
