// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type FleetMetricName string

const (
	FleetMetricNameProvisionedTotal     FleetMetricName = "provisionedTotal"
	FleetMetricNameProvisionedBareMetal FleetMetricName = "provisionedBareMetal"
	FleetMetricNameProvisionedCloud     FleetMetricName = "provisionedCloud"
	FleetMetricNameUtilized             FleetMetricName = "utilized"
)

func (e FleetMetricName) ToPointer() *FleetMetricName {
	return &e
}
