// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type FleetRegionConfig struct {
	CloudMinVcpus int `json:"cloudMinVcpus"`
}

func (o *FleetRegionConfig) GetCloudMinVcpus() int {
	if o == nil {
		return 0
	}
	return o.CloudMinVcpus
}
