// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// ProcessMetricName - Available metrics to query over time.
type ProcessMetricName string

const (
	ProcessMetricNameCPU               ProcessMetricName = "cpu"
	ProcessMetricNameMemory            ProcessMetricName = "memory"
	ProcessMetricNameRateEgress        ProcessMetricName = "rateEgress"
	ProcessMetricNameTotalEgress       ProcessMetricName = "totalEgress"
	ProcessMetricNameActiveConnections ProcessMetricName = "activeConnections"
)

func (e ProcessMetricName) ToPointer() *ProcessMetricName {
	return &e
}
