// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type VerificationEmailRequest struct {
	UserID string `json:"userId"`
}

func (o *VerificationEmailRequest) GetUserID() string {
	if o == nil {
		return ""
	}
	return o.UserID
}
