// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/hathora/ci/internal/sdk/pkg/models/shared"
	"net/http"
)

type CreateDeploymentGlobals struct {
	AppID *string `pathParam:"style=simple,explode=false,name=appId"`
}

func (o *CreateDeploymentGlobals) GetAppID() *string {
	if o == nil {
		return nil
	}
	return o.AppID
}

type CreateDeploymentRequest struct {
	BuildID            int                       `pathParam:"style=simple,explode=false,name=buildId"`
	DeploymentConfigV2 shared.DeploymentConfigV2 `request:"mediaType=application/json"`
	AppID              *string                   `pathParam:"style=simple,explode=false,name=appId"`
}

func (o *CreateDeploymentRequest) GetBuildID() int {
	if o == nil {
		return 0
	}
	return o.BuildID
}

func (o *CreateDeploymentRequest) GetDeploymentConfigV2() shared.DeploymentConfigV2 {
	if o == nil {
		return shared.DeploymentConfigV2{}
	}
	return o.DeploymentConfigV2
}

func (o *CreateDeploymentRequest) GetAppID() *string {
	if o == nil {
		return nil
	}
	return o.AppID
}

type CreateDeploymentResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse  *http.Response
	DeploymentV2 *shared.DeploymentV2
}

func (o *CreateDeploymentResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *CreateDeploymentResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *CreateDeploymentResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *CreateDeploymentResponse) GetDeploymentV2() *shared.DeploymentV2 {
	if o == nil {
		return nil
	}
	return o.DeploymentV2
}
