name: Certificate Renewal

on:
  schedule:
    # Run at 10am PST / 5pm UTC weekdays
    - cron: '0 17 * * 1-5'
  workflow_dispatch:

env:
  AWS_ACCOUNT_ID: REPLACE_ME
  AWS_ROLE_ARN: REPLACE_ME
  TERRAFORM_PATH: terraform

jobs:

  renewal:
    name: Certificate Renewal
    runs-on: ubuntu-latest
    steps:

     - name: Setup Terraform
       uses: hashicorp/setup-terraform@v3
       with:
         terraform_version: "1.9.4"

     - name: Configure AWS Credentials
       uses: aws-actions/configure-aws-credentials@v4
       with:
         role-to-assume: ${{ env.AWS_ROLE_ARN }}
         aws-region: us-west-2

     - name: Terraform Init
       run: terraform init
       working-directory: ${{ env.TERRAFORM_PATH }}

     - name: Terraform Apply
       run: terraform apply -auto-approve
       working-directory: ${{ env.TERRAFORM_PATH }}
